-- ============================================================
-- seed.sql — Yosi Puzzle Catalog, March 2026
-- Run: supabase db seed  (or paste into Supabase SQL editor)
-- ============================================================

INSERT INTO puzzles (id, puzzle_date, engine_type, config, day_of_week, week_number, grade_band) VALUES

-- Day 1 · Mar 1 · Deduction · Week 1
('2026-03-01', '2026-03-01', 'deduction',
 '{"id":"deduction_20260301","title":"Mystery: The Missing Saffron","storyBeat":"The first morning of spring blew warm off the river, carrying the scent of jasmine and something missing. Old Mehta the spice-seller arrived at his stall to find his finest saffron gone — the threads he had been saving for the Vernal Festival. Chatur set her clay cup of chai on the step and narrowed her eyes. ''Someone was here before dawn,'' she said. ''Let us ask the lane.''","hint":"Chatur whispers: ''One clue names who was *not* there. Another names where the saffron was *last* seen. Put them together.''","winMessage":"The saffron was found tucked beneath a jute sack at the Bazaar stall — and young Ramu confessed he had borrowed it meaning to return it before sunrise. Chatur smiled. ''Borrowed, yes. But the lane remembers everything.''","grade":"1-3","category":"2.1","categories":[{"name":"Suspect","icon":"🧑","items":[{"name":"Ramu","icon":"👦"},{"name":"Priya","icon":"👧"}]},{"name":"Location","icon":"📍","items":[{"name":"Bazaar","icon":"🏪"},{"name":"River Ghat","icon":"⛵"}]}],"clues":[{"id":1,"text":"Priya was seen at the River Ghat fetching water well before the stall opened — she never came near the Bazaar."},{"id":2,"text":"The missing saffron jar was last spotted at the Bazaar stall, not at any riverside location."}],"solution":{"Suspect":"Ramu","Location":"Bazaar"}}',
 0, 1, '1-3'),

-- Day 2 · Mar 2 · Flow · Week 1
('2026-03-02', '2026-03-02', 'flow',
 '{"id":"flow_20260302","title":"Threads of the Morning Market","storyBeat":"Chatur loved the way the Bazaar woke up — bolt by bolt, stall by stall, each color unfurling like a flag claiming its corner of the lane.","hint":"Chatur says: ''Start from a corner and see which color has the clearest road — then let the others follow.''","winMessage":"Every bolt of cloth found its matching bale, and the lane shimmered like a festival banner.","grade":"2-3","category":"1.2","grid":4,"pairs":[{"id":"R","color":"#e05050","start":[0,0],"end":[3,1]},{"id":"B","color":"#4a90d9","start":[0,2],"end":[2,1]},{"id":"G","color":"#3a7d44","start":[0,3],"end":[2,2]},{"id":"Y","color":"#e8a820","start":[2,3],"end":[3,2]}]}',
 1, 1, '2-3'),

-- Day 3 · Mar 3 · Deduction · Week 1
('2026-03-03', '2026-03-03', 'deduction',
 '{"id":"deduction_20260303","title":"Mystery: The Borrowed Ferry Token","storyBeat":"The ferryman Gopal arrived at the Ghat to find his iron token gone from the hook beside his oar.","hint":"Chatur says: ''One suspect was never near the water. The clue about the token''s last sighting tells you everything.''","winMessage":"Lakshmi had accidentally picked up the token thinking it was her own market badge. She returned it with a sheepish smile and a gift of fresh hilsa.","grade":"1-3","category":"2.1","categories":[{"name":"Suspect","icon":"🧑","items":[{"name":"Lakshmi","icon":"👩"},{"name":"Deepak","icon":"👨"}]},{"name":"Location","icon":"📍","items":[{"name":"River Ghat","icon":"⛵"},{"name":"School of Questions","icon":"🏫"}]}],"clues":[{"id":1,"text":"Deepak spent the whole of yesterday evening at the School of Questions attending the scholar''s lecture — he did not visit the Ghat."},{"id":2,"text":"The ferry token was last seen hanging on Gopal''s hook at the River Ghat before it disappeared."}],"solution":{"Suspect":"Lakshmi","Location":"River Ghat"}}',
 2, 1, '1-3'),

-- Day 4 · Mar 4 · Connections · Week 1
('2026-03-04', '2026-03-04', 'connections',
 '{"id":"connections_20260304","title":"What the Bazaar Knows","storyBeat":"Chatur sat atop a sack of lentils at the edge of the Bazaar and watched the world sort itself.","hint":"Chatur says: ''Think about what each thing *does* in Budhipur, not just what it *is*. One group will surprise you.''","winMessage":"Hari stared at the sorted piles with new eyes. ''I see it now,'' he said.","grade":"3-5","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Things sold at the spice stalls","connection":"All are spices traded in Budhipur''s Spice Quarter","tiles":[{"text":"Saffron","icon":"🌸"},{"text":"Turmeric","icon":"🟡"},{"text":"Cardamom","icon":"🫘"},{"text":"Cumin","icon":"🌿"}]},{"id":"g2","color":"#4a90d9","label":"Things that move on the river","connection":"All travel along Budhipur''s great river","tiles":[{"text":"Ferry","icon":"⛵"},{"text":"Log Raft","icon":"🪵"},{"text":"Coracle","icon":"🛶"},{"text":"Lotus Boat","icon":"🪷"}]},{"id":"g3","color":"#e8a820","label":"Things kept in the Old Archive","connection":"All are stored in the Archivist''s care","tiles":[{"text":"Scroll","icon":"📜"},{"text":"Wax Seal","icon":"🔴"},{"text":"Copper Plate","icon":"🥉"},{"text":"Reed Pen","icon":"✒️"}]},{"id":"g4","color":"#c060c0","label":"Things Chatur keeps in her satchel","connection":"All are found in Chatur''s famous battered satchel","tiles":[{"text":"Chalk Stick","icon":"🖍️"},{"text":"String Loop","icon":"🪢"},{"text":"Pebble","icon":"🪨"},{"text":"Folded Map","icon":"🗺️"}]}]}',
 3, 1, '3-5'),

-- Day 5 · Mar 5 · Connections · Week 1
('2026-03-05', '2026-03-05', 'connections',
 '{"id":"connections_20260305","title":"Voices of the Festival","storyBeat":"The Vernal Festival was three days away and all of Budhipur hummed with preparation.","hint":"Chatur says: ''Listen for what each word *does* during the festival — not just how it sounds.''","winMessage":"The Archivist smiled — a rare sight — and said the city spoke more clearly when you sorted it properly.","grade":"3-5","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Festival sweets of Budhipur","connection":"All are sweets made and eaten during the Vernal Festival","tiles":[{"text":"Jalebi","icon":"🟠"},{"text":"Ladoo","icon":"🟡"},{"text":"Barfi","icon":"🍬"},{"text":"Halwa","icon":"🍮"}]},{"id":"g2","color":"#4a90d9","label":"Sounds heard at the festival","connection":"All are sounds that fill Budhipur during celebrations","tiles":[{"text":"Dholak","icon":"🥁"},{"text":"Conch","icon":"🐚"},{"text":"Ghungroo","icon":"🔔"},{"text":"Shehnai","icon":"🎵"}]},{"id":"g3","color":"#e8a820","label":"Things strung up for decoration","connection":"All are hung across lanes and doorways to decorate","tiles":[{"text":"Marigold","icon":"🌼"},{"text":"Mango Leaf","icon":"🍃"},{"text":"Paper Lantern","icon":"🏮"},{"text":"Banana Blossom","icon":"🌺"}]},{"id":"g4","color":"#c060c0","label":"Things that go in a puja thali","connection":"All are placed on the offering plate during the festival ritual","tiles":[{"text":"Kumkum","icon":"🔴"},{"text":"Agarbatti","icon":"🕯️"},{"text":"Rice Grain","icon":"🌾"},{"text":"Coconut","icon":"🥥"}]}]}',
 4, 1, '3-5'),

-- Day 6 · Mar 6 · Sudoku · Week 1
('2026-03-06', '2026-03-06', 'sudoku',
 '{"id":"sudoku_20260306","title":"The Archivist''s Counting Squares","storyBeat":"Every Friday the Archivist tallied his shelves — four kinds of scrolls, four rows of cedar shelving, four columns of reed baskets.","hint":"Chatur says: ''Each row, each column, each square of four must hold every number exactly once.''","winMessage":"The Archivist examined the completed grid and found not one error.","grade":"2-3","category":"2.4","size":4,"digits":[1,2,3,4],"givens":[1,0,0,4,3,0,0,2,2,0,0,3,4,0,0,1],"solution":[1,2,3,4,3,4,1,2,2,1,4,3,4,3,2,1],"regions":[[0,1,4,5],[2,3,6,7],[8,9,12,13],[10,11,14,15]]}',
 5, 1, '2-3'),

-- Day 7 · Mar 7 · Flow · Week 1
('2026-03-07', '2026-03-07', 'flow',
 '{"id":"flow_20260307","title":"Water Channels of the Ghat","storyBeat":"On Saturday mornings, the Ghat was all work and splash.","hint":"Chatur says: ''The channels cannot cross — but every inch of stone must carry water. Plan the longer routes first.''","winMessage":"Water flowed to every basin and the washers sang their morning songs.","grade":"2-3","category":"1.2","grid":4,"pairs":[{"id":"R","color":"#e05050","start":[0,0],"end":[2,3]},{"id":"B","color":"#4a90d9","start":[0,2],"end":[3,3]},{"id":"G","color":"#3a7d44","start":[1,1],"end":[3,0]},{"id":"Y","color":"#e8a820","start":[0,3],"end":[3,1]}]}',
 6, 1, '2-3'),

-- Day 8 · Mar 8 · Sudoku · Week 2
('2026-03-08', '2026-03-08', 'sudoku',
 '{"id":"sudoku_20260308","title":"The Merchant''s Ledger Squares","storyBeat":"Merchant Vishnu kept his accounts in a grid — four goods across, four seasons down, never repeating a tally.","hint":"Chatur says: ''Look at each row and column for what is missing.''","winMessage":"Merchant Vishnu checked every number twice, then hired Chatur as a part-time auditor on the spot.","grade":"2-4","category":"2.4","size":4,"digits":[1,2,3,4],"givens":[0,2,0,4,0,0,1,0,0,1,0,0,4,0,2,0],"solution":[1,2,3,4,3,4,1,2,2,1,4,3,4,3,2,1],"regions":[[0,1,4,5],[2,3,6,7],[8,9,12,13],[10,11,14,15]]}',
 0, 2, '2-4'),

-- Day 9 · Mar 9 · Flow · Week 2
('2026-03-09', '2026-03-09', 'flow',
 '{"id":"flow_20260309","title":"The Lamp-Lighter''s Routes","storyBeat":"Each evening before dusk, the lamp-lighter of Budhipur walked every lane to light the oil lamps.","hint":"Chatur says: ''On a five-by-five grid the paths feel tight, but every cell must glow. The corners tend to help you begin.''","winMessage":"Every lamp blazed that evening, and not a single path had crossed another.","grade":"4-6","category":"1.2","grid":5,"pairs":[{"id":"R","color":"#e05050","start":[0,1],"end":[1,0]},{"id":"B","color":"#4a90d9","start":[0,4],"end":[3,3]},{"id":"G","color":"#3a7d44","start":[0,3],"end":[4,1]},{"id":"Y","color":"#e8a820","start":[1,1],"end":[4,0]},{"id":"P","color":"#9b59b6","start":[2,4],"end":[4,2]}]}',
 1, 2, '4-6'),

-- Day 10 · Mar 10 · Deduction · Week 2
('2026-03-10', '2026-03-10', 'deduction',
 '{"id":"deduction_20260310","title":"Mystery: The Vanished Scroll","storyBeat":"The Archivist kept three hundred scrolls, and he knew each one the way a shepherd knows his flock.","hint":"Chatur says: ''Eliminate each suspect from their alibi location first.''","winMessage":"Scholar Anita had borrowed the scroll to settle a bet about flood seasons.","grade":"4-6","category":"2.1","categories":[{"name":"Suspect","icon":"🧑","items":[{"name":"Scholar Anita","icon":"👩‍🎓"},{"name":"Trader Basu","icon":"🧔"},{"name":"Ferryman Gopal","icon":"⛵"}]},{"name":"Location","icon":"📍","items":[{"name":"Reading Room","icon":"📖"},{"name":"Spice Quarter","icon":"🌶️"},{"name":"River Ghat","icon":"🌊"}]}],"clues":[{"id":1,"text":"Trader Basu cannot read the old script the scroll is written in — he would have no use for it."},{"id":2,"text":"Ferryman Gopal was at the River Ghat all day Tuesday; the Archive''s visitors'' stone shows he never signed in."},{"id":3,"text":"The scroll was last spotted inside the Archive''s Reading Room, not at any outdoor location."}],"solution":{"Suspect":"Scholar Anita","Location":"Reading Room"}}',
 2, 2, '4-6'),

-- Day 11 · Mar 11 · Connections · Week 2
('2026-03-11', '2026-03-11', 'connections',
 '{"id":"connections_20260311","title":"Trades of Chatur''s Lane","storyBeat":"Chatur''s lane was short — barely forty steps end to end — but it held a whole economy.","hint":"Chatur says: ''Think about the *craft*, not the material.''","winMessage":"Hari sorted every item perfectly — except he almost put ''Needle'' with the cobbler.","grade":"4-6","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Tools of the scribe''s trade","connection":"All are used by the scribe on Chatur''s Lane","tiles":[{"text":"Reed Pen","icon":"✒️"},{"text":"Inkpot","icon":"🖋️"},{"text":"Wax Stick","icon":"🕯️"},{"text":"Parchment","icon":"📜"}]},{"id":"g2","color":"#4a90d9","label":"Tools of the dyer''s craft","connection":"All are used by the dyer to colour cloth in Budhipur","tiles":[{"text":"Indigo Cake","icon":"🟦"},{"text":"Mordant Pot","icon":"🫙"},{"text":"Drying Hook","icon":"🪝"},{"text":"Teak Paddle","icon":"🏏"}]},{"id":"g3","color":"#e8a820","label":"Tools of the cobbler''s workshop","connection":"All are found at the cobbler''s bench on the lane","tiles":[{"text":"Awl","icon":"🔧"},{"text":"Leather Strip","icon":"🟫"},{"text":"Wooden Last","icon":"🪵"},{"text":"Cobbler''s Wax","icon":"⬛"}]},{"id":"g4","color":"#c060c0","label":"Things the weaver passes through the loom","connection":"All travel through the weaver''s loom to make cloth","tiles":[{"text":"Warp Thread","icon":"🧵"},{"text":"Weft Yarn","icon":"🪢"},{"text":"Shuttle","icon":"🚀"},{"text":"Heddle Rod","icon":"📏"}]}]}',
 3, 2, '4-6'),

-- Day 12 · Mar 12 · Connections · Week 2
('2026-03-12', '2026-03-12', 'connections',
 '{"id":"connections_20260312","title":"River Knowledge","storyBeat":"The schoolmaster had a lesson every Thursday that he called River Knowledge.","hint":"Chatur says: ''Some of these words feel like they belong together but are false friends.''","winMessage":"The schoolmaster said nothing for a long moment after Chatur presented her groupings.","grade":"4-6","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Types of boats on Budhipur''s river","connection":"All are vessels that navigate the great river","tiles":[{"text":"Coracle","icon":"🛶"},{"text":"Dugout","icon":"🪵"},{"text":"Barge","icon":"⛴️"},{"text":"Punt","icon":"🚣"}]},{"id":"g2","color":"#4a90d9","label":"Things found in the river mud","connection":"All are discovered in the riverbank mud at low water","tiles":[{"text":"Clay Bead","icon":"🟤"},{"text":"Snail Shell","icon":"🐌"},{"text":"Bronze Coin","icon":"🥉"},{"text":"Reed Root","icon":"🌱"}]},{"id":"g3","color":"#e8a820","label":"Words for the river''s moods","connection":"All describe how the great river behaves at different seasons","tiles":[{"text":"Swollen","icon":"💧"},{"text":"Sluggish","icon":"🐢"},{"text":"Tawny","icon":"🟡"},{"text":"Silted","icon":"⏳"}]},{"id":"g4","color":"#c060c0","label":"Things the ferryman carries besides passengers","connection":"All are goods Gopal the ferryman secretly transports","tiles":[{"text":"Rumour","icon":"🗣️"},{"text":"Letter","icon":"✉️"},{"text":"Smuggled Nutmeg","icon":"🫘"},{"text":"Lost Umbrella","icon":"☂️"}]}]}',
 4, 2, '4-6'),

-- Day 13 · Mar 13 · Sudoku · Week 2
('2026-03-13', '2026-03-13', 'sudoku',
 '{"id":"sudoku_20260313","title":"Seeds in the Planting Square","storyBeat":"The school garden had four beds arranged in a square, and the gardener-teacher had a rule.","hint":"Chatur says: ''Two numbers are already in the right place. Let each box of four show you which two are missing.''","winMessage":"The garden grew exactly as planned, and every bed bloomed with its appointed flower.","grade":"2-4","category":"2.4","size":4,"digits":[1,2,3,4],"givens":[2,0,0,3,4,0,0,1,0,2,3,0,0,4,1,0],"solution":[2,1,4,3,4,3,2,1,1,2,3,4,3,4,1,2],"regions":[[0,1,4,5],[2,3,6,7],[8,9,12,13],[10,11,14,15]]}',
 5, 2, '2-4'),

-- Day 14 · Mar 14 · Flow · Week 2
('2026-03-14', '2026-03-14', 'flow',
 '{"id":"flow_20260314","title":"Silk Routes Through the Quarter","storyBeat":"The Silk Quarter of Budhipur was a knot of narrow alleys, and on festival week every merchant needed a clear path.","hint":"Chatur says: ''The centre of the grid is the most contested passage. Assign it first, and the rest will breathe.''","winMessage":"All five merchant-carts reached their stalls without a single collision.","grade":"4-6","category":"1.2","grid":5,"pairs":[{"id":"R","color":"#e05050","start":[0,0],"end":[4,3]},{"id":"B","color":"#4a90d9","start":[0,4],"end":[3,0]},{"id":"G","color":"#3a7d44","start":[1,2],"end":[4,4]},{"id":"Y","color":"#e8a820","start":[0,1],"end":[4,1]},{"id":"P","color":"#9b59b6","start":[2,4],"end":[3,2]}]}',
 6, 2, '4-6'),

-- Day 15 · Mar 15 · Deduction · Week 3
('2026-03-15', '2026-03-15', 'deduction',
 '{"id":"deduction_20260315","title":"Mystery: The Stolen Festival Drum","storyBeat":"Three days before the Vernal Festival, the great ceremonial drum went missing from the music-keeper''s locked room.","hint":"Chatur says: ''Cross out each suspect from every location they could not have visited.''","winMessage":"The drum was found wrapped in a shawl in the Costume Room, moved there by the Costume-Keeper.","grade":"4-6","category":"2.1","categories":[{"name":"Suspect","icon":"🧑","items":[{"name":"Music-Keeper","icon":"🎵"},{"name":"Costume-Keeper","icon":"👘"},{"name":"Gate-Warden","icon":"🚪"}]},{"name":"Room","icon":"🏛️","items":[{"name":"Costume Room","icon":"👗"},{"name":"Lamp Store","icon":"🪔"},{"name":"Roof Terrace","icon":"🏠"}]}],"clues":[{"id":1,"text":"The Music-Keeper''s own room was locked from outside all night — so the Music-Keeper could not have moved the drum elsewhere."},{"id":2,"text":"The Gate-Warden was stationed at the main gate from sunset to sunrise and never once entered the building interior."},{"id":3,"text":"The drum is too heavy to carry up the external staircase to the Roof Terrace — that location is impossible for any single person."}],"solution":{"Suspect":"Costume-Keeper","Room":"Costume Room"}}',
 0, 3, '4-6'),

-- Day 16 · Mar 16 · Flow · Week 3
('2026-03-16', '2026-03-16', 'flow',
 '{"id":"flow_20260316","title":"Messenger Birds and Their Roosts","storyBeat":"The Archive kept six messenger pigeons, each banded with a different colour, each flying a dedicated route.","hint":"Chatur says: ''On a six-by-six sky, the wingtips must never touch. Let the bird farthest from home fly first.''","winMessage":"Every pigeon found its roost before the evening bell. The bird-keeper called it a miracle. Chatur called it geometry.","grade":"4-6","category":"1.2","grid":6,"pairs":[{"id":"R","color":"#e05050","start":[0,0],"end":[3,2]},{"id":"G","color":"#3a7d44","start":[0,3],"end":[3,5]},{"id":"B","color":"#4a90d9","start":[1,0],"end":[4,0]},{"id":"Y","color":"#e8a820","start":[1,3],"end":[4,3]},{"id":"P","color":"#9b59b6","start":[3,1],"end":[5,0]},{"id":"O","color":"#e8803a","start":[3,4],"end":[5,3]}]}',
 1, 3, '4-6'),

-- Day 17 · Mar 17 · Deduction · Week 3
('2026-03-17', '2026-03-17', 'deduction',
 '{"id":"deduction_20260317","title":"Mystery: The Wrong Spice Shipment","storyBeat":"Four sacks arrived at the Spice Quarter on Tuesday, but the labels had been swapped in transit.","hint":"Chatur says: ''Pair each merchant with only the spice they ordered.''","winMessage":"In five minutes exactly, Chatur had sorted all four sacks. Everyone bought her lunch.","grade":"4-6","category":"2.1","categories":[{"name":"Merchant","icon":"🧑‍💼","items":[{"name":"Tara","icon":"👩"},{"name":"Nandan","icon":"👨"},{"name":"Bela","icon":"👧"}]},{"name":"Spice","icon":"🌶️","items":[{"name":"Saffron","icon":"🌸"},{"name":"Cumin","icon":"🌿"},{"name":"Cardamom","icon":"🫘"}]}],"clues":[{"id":1,"text":"Nandan is the only one who orders seeds rather than threads or flowers — his spice is cumin."},{"id":2,"text":"Bela has an allergy to anything from the ginger family; she never orders saffron because of the cost."},{"id":3,"text":"Tara runs the most expensive stall in the Quarter and always buys the rarest available spice."}],"solution":{"Merchant":"Tara","Spice":"Saffron"}}',
 2, 3, '4-6'),

-- Day 18 · Mar 18 · Connections · Week 3
('2026-03-18', '2026-03-18', 'connections',
 '{"id":"connections_20260318","title":"The Archivist''s Vocabulary","storyBeat":"The Archivist believed that every word in the city had a secret twin.","hint":"Chatur says: ''The Archivist is testing your knowledge of what things *are used for*, not what they are made of.''","winMessage":"Chatur sorted the sixteen words without hesitation, except for one moment.","grade":"5-7","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Things used to measure in Budhipur","connection":"All are measuring instruments or units in the city","tiles":[{"text":"Cubit Rod","icon":"📏"},{"text":"Balance Stone","icon":"⚖️"},{"text":"Water Clock","icon":"⏳"},{"text":"Shadow Pole","icon":"🪧"}]},{"id":"g2","color":"#4a90d9","label":"Things a physician carries","connection":"All are found in a Budhipur physician''s bag","tiles":[{"text":"Silver Needle","icon":"🪡"},{"text":"Neem Paste","icon":"🟢"},{"text":"Copper Cup","icon":"🥤"},{"text":"Dried Ginger","icon":"🫚"}]},{"id":"g3","color":"#e8a820","label":"Words for kinds of silence in Budhipur","connection":"All are types of silence the city recognises and names","tiles":[{"text":"Archive Quiet","icon":"🤫"},{"text":"Midday Hush","icon":"☀️"},{"text":"River Lull","icon":"🌊"},{"text":"Festival Pause","icon":"🎉"}]},{"id":"g4","color":"#c060c0","label":"Things that mark a boundary in the city","connection":"All are used to mark where one quarter ends and another begins","tiles":[{"text":"Painted Stone","icon":"🟠"},{"text":"Neem Post","icon":"🌳"},{"text":"Iron Chain","icon":"⛓️"},{"text":"Oil Lamp Row","icon":"🪔"}]}]}',
 3, 3, '5-7'),

-- Day 19 · Mar 19 · Connections · Week 3
('2026-03-19', '2026-03-19', 'connections',
 '{"id":"connections_20260319","title":"Street Foods After Midnight","storyBeat":"The Vernal Festival ran past midnight, and Chatur and Hari walked the illuminated lanes.","hint":"Chatur says: ''Think about how each item is cooked or carried, not just what it tastes like.''","winMessage":"They ate everything on the list before the bells struck one.","grade":"5-7","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Street foods fried in oil","connection":"All are deep-fried street foods sold at Budhipur''s night stalls","tiles":[{"text":"Pakoda","icon":"🫓"},{"text":"Puri","icon":"🫔"},{"text":"Bonda","icon":"🟡"},{"text":"Mathri","icon":"🍘"}]},{"id":"g2","color":"#4a90d9","label":"Things served on a leaf plate","connection":"All are traditionally served on banana or sal leaf","tiles":[{"text":"Khichdi","icon":"🍲"},{"text":"Tamarind Chutney","icon":"🟤"},{"text":"Roasted Gram","icon":"🫘"},{"text":"Rice Pudding","icon":"🍮"}]},{"id":"g3","color":"#e8a820","label":"Things skewered on a stick","connection":"All are street foods sold on skewers at the festival","tiles":[{"text":"Corn Cob","icon":"🌽"},{"text":"Paneer Tikka","icon":"🟨"},{"text":"Sweet Potato","icon":"🍠"},{"text":"Spiced Mushroom","icon":"🍄"}]},{"id":"g4","color":"#c060c0","label":"Things Chatur always refuses but eats anyway","connection":"All are foods Chatur claims she dislikes but always finishes","tiles":[{"text":"Sugarcane Juice","icon":"🥤"},{"text":"Coconut Burfi","icon":"🥥"},{"text":"Fried Banana","icon":"🍌"},{"text":"Cardamom Milk","icon":"🥛"}]}]}',
 4, 3, '5-7'),

-- Day 20 · Mar 20 · Sudoku · Week 3
('2026-03-20', '2026-03-20', 'sudoku',
 '{"id":"sudoku_20260320","title":"The School''s Seating Puzzle","storyBeat":"The School of Questions had a new master who insisted that no two students from the same village sit in the same row or column.","hint":"Chatur says: ''Fewer given numbers means you must use the grid''s own logic harder.''","winMessage":"Every student from every village was properly seated.","grade":"4-6","category":"2.4","size":4,"digits":[1,2,3,4],"givens":[0,1,0,0,0,3,0,1,1,0,0,4,0,0,1,0],"solution":[2,1,4,3,4,3,2,1,1,2,3,4,3,4,1,2],"regions":[[0,1,4,5],[2,3,6,7],[8,9,12,13],[10,11,14,15]]}',
 5, 3, '4-6'),

-- Day 21 · Mar 21 · Flow · Week 3
('2026-03-21', '2026-03-21', 'flow',
 '{"id":"flow_20260321","title":"Festival Procession Paths","storyBeat":"The Vernal Festival procession had five parade groups, each assigned a colour and a route through the six-lane city.","hint":"Chatur says: ''A festival route that traps itself in a corner has brought the parade to a standstill. Think ahead before you march.''","winMessage":"Five processions wound through Budhipur without a single tangle.","grade":"4-6","category":"1.2","grid":6,"pairs":[{"id":"R","color":"#e05050","start":[0,0],"end":[5,0]},{"id":"B","color":"#4a90d9","start":[0,5],"end":[5,5]},{"id":"G","color":"#3a7d44","start":[0,1],"end":[1,1]},{"id":"Y","color":"#e8a820","start":[2,1],"end":[3,1]},{"id":"P","color":"#9b59b6","start":[4,1],"end":[5,1]}]}',
 6, 3, '4-6'),

-- Day 22 · Mar 22 · Deduction · Week 4
('2026-03-22', '2026-03-22', 'deduction',
 '{"id":"deduction_20260322","title":"Mystery: The Night of Four Accusations","storyBeat":"On the night of the festival''s grand finale, four things went missing from four different corners of Budhipur.","hint":"Chatur says: ''This one requires you to track four suspects across four locations. Build a grid in your mind.''","winMessage":"All four culprits were found, all four items returned before dawn.","grade":"7-10","category":"2.1","categories":[{"name":"Suspect","icon":"🧑","items":[{"name":"Hari","icon":"👦"},{"name":"Nandan","icon":"👨"},{"name":"Lakshmi","icon":"👩"},{"name":"Scholar Anita","icon":"👩‍🎓"}]},{"name":"Stolen Item","icon":"📦","items":[{"name":"Copper Lamp","icon":"🪔"},{"name":"Archivist''s Seal","icon":"🔴"},{"name":"Bolt of Silk","icon":"🧣"},{"name":"Headmaster''s Bell","icon":"🔔"}]}],"clues":[{"id":1,"text":"Hari cannot read the Archivist''s old script — the seal was not taken by Hari."},{"id":2,"text":"Nandan is a cloth trader; witnesses saw him lingering near the Silk Quarter stalls that evening."},{"id":3,"text":"Lakshmi needed light at the fish-stall that ran past midnight; she was seen carrying something lamp-shaped."},{"id":4,"text":"Scholar Anita had argued with the headmaster that morning about the bell schedule."},{"id":5,"text":"The Archivist''s seal requires knowledge of where it is kept — only a regular Archive visitor would know."}],"solution":{"Suspect":"Scholar Anita","Stolen Item":"Archivist''s Seal"}}',
 0, 4, '7-10'),

-- Day 23 · Mar 23 · Flow · Week 4
('2026-03-23', '2026-03-23', 'flow',
 '{"id":"flow_20260323","title":"The Cartographer''s Proof","storyBeat":"The old cartographer of Budhipur had drawn the city''s secret water-veins — underground channels that fed every well.","hint":"Chatur says: ''Fill every cell, and let no channel cross another. The hardest route is the one you must plan last of all.''","winMessage":"The council framed the completed map and hung it in the Archive.","grade":"7-9","category":"1.2","grid":6,"pairs":[{"id":"R","color":"#e05050","start":[0,0],"end":[5,2]},{"id":"B","color":"#4a90d9","start":[0,5],"end":[5,3]},{"id":"G","color":"#3a7d44","start":[1,0],"end":[4,5]},{"id":"Y","color":"#e8a820","start":[0,3],"end":[5,0]},{"id":"P","color":"#9b59b6","start":[2,1],"end":[3,4]},{"id":"O","color":"#e8803a","start":[0,2],"end":[5,5]}]}',
 1, 4, '7-9'),

-- Day 24 · Mar 24 · Deduction · Week 4
('2026-03-24', '2026-03-24', 'deduction',
 '{"id":"deduction_20260324","title":"Mystery: Who Forged the Merchant''s Seal?","storyBeat":"A forged seal had been used to falsify four trading ledgers in the Bazaar.","hint":"Chatur says: ''The time of forgery is as important as the forger. Two clues pin the time; two more pin the person.''","winMessage":"The forger turned out to be the magistrate''s own clerk, who had been padding trade numbers for a year.","grade":"7-10","category":"2.1","categories":[{"name":"Forger","icon":"🧑‍💼","items":[{"name":"Ravi the Clerk","icon":"📋"},{"name":"Mira the Printer","icon":"🖨️"},{"name":"Suman the Wax-Worker","icon":"🕯️"},{"name":"Old Mehta","icon":"👴"}]},{"name":"Time of Forgery","icon":"🕐","items":[{"name":"Dawn","icon":"🌅"},{"name":"Midday","icon":"☀️"},{"name":"Dusk","icon":"🌆"},{"name":"Midnight","icon":"🌙"}]}],"clues":[{"id":1,"text":"Old Mehta is nearly blind by lamplight — he cannot work at dusk or midnight."},{"id":2,"text":"Mira the Printer runs her press only at midday; she is never at her workshop at dawn."},{"id":3,"text":"A witness saw Suman the Wax-Worker at the temple at both dawn and dusk that week."},{"id":4,"text":"The forgeries show characteristics of a fine quill pen — only a clerk or merchant would use a quill."},{"id":5,"text":"The ink used dries only in darkness, which means the forgery was done at a time with no natural light."},{"id":6,"text":"Old Mehta was seen at the Ghat the entire evening of the forgery — several people confirm this."}],"solution":{"Forger":"Ravi the Clerk","Time of Forgery":"Midnight"}}',
 2, 4, '7-10'),

-- Day 25 · Mar 25 · Connections · Week 4
('2026-03-25', '2026-03-25', 'connections',
 '{"id":"connections_20260325","title":"Things the City Keeps Secret","storyBeat":"The Archivist told Chatur once that Budhipur kept its truths the way a mango keeps its stone.","hint":"Chatur says: ''Do not trust your first instinct. The word that looks most alone belongs to the hardest group.''","winMessage":"Chatur placed the last tile and looked up. The Archivist was asleep in his chair.","grade":"6-9","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Ancient guilds of Budhipur","connection":"All are names of the city''s oldest professional guilds from the founding records","tiles":[{"text":"The Weighers","icon":"⚖️"},{"text":"The Flamekeepers","icon":"🔥"},{"text":"The Seedmen","icon":"🌱"},{"text":"The Bridge-Walkers","icon":"🌉"}]},{"id":"g2","color":"#4a90d9","label":"Hidden rooms in the Old Archive","connection":"All are secret rooms the Archivist has shown only to Chatur","tiles":[{"text":"The Doubt Room","icon":"❓"},{"text":"The Listening Hall","icon":"👂"},{"text":"The Smell Vault","icon":"👃"},{"text":"The Forgetting Chamber","icon":"🌫️"}]},{"id":"g3","color":"#e8a820","label":"Things Budhipur does at exactly noon","connection":"All are rituals or events the whole city performs at midday","tiles":[{"text":"Bell-Silence","icon":"🔕"},{"text":"Shadow-Read","icon":"🌑"},{"text":"Water-Pour","icon":"💧"},{"text":"Dust-Sweep","icon":"🧹"}]},{"id":"g4","color":"#c060c0","label":"Words Chatur has never spoken aloud","connection":"All are words Chatur carries in her notebook but never says","tiles":[{"text":"Loneliness","icon":"🫥"},{"text":"Enough","icon":"✋"},{"text":"Home","icon":"🏠"},{"text":"Finished","icon":"🏁"}]}]}',
 3, 4, '6-9'),

-- Day 26 · Mar 26 · Connections · Week 4
('2026-03-26', '2026-03-26', 'connections',
 '{"id":"connections_20260326","title":"The Merchant''s Four Languages","storyBeat":"The great merchants of Budhipur spoke four languages simultaneously.","hint":"Chatur says: ''The language of silence is the hardest. Those four words seem to mean nothing — but they mean the most.''","winMessage":"''The language of silence,'' Hari said, ''is just things that stop.''","grade":"6-9","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Language of goods — things that change hands","connection":"All are objects physically exchanged in the Bazaar''s trade language","tiles":[{"text":"Sample Pinch","icon":"🤌"},{"text":"First Weight","icon":"⚖️"},{"text":"Deposit Grain","icon":"🌾"},{"text":"Pledge Thread","icon":"🧵"}]},{"id":"g2","color":"#4a90d9","label":"Language of gesture — merchant signals","connection":"All are hand or body gestures that merchants use to signal prices without words","tiles":[{"text":"Chin Tilt","icon":"😤"},{"text":"Wrist Turn","icon":"🫳"},{"text":"Finger Splay","icon":"🖐️"},{"text":"Eye-Flick","icon":"👁️"}]},{"id":"g3","color":"#e8a820","label":"Language of rumour — what the Bazaar whispers","connection":"All are types of rumour that circulate in Budhipur''s marketplace","tiles":[{"text":"Shortage Warning","icon":"⚠️"},{"text":"Price Whisper","icon":"💬"},{"text":"Arrival Rumour","icon":"🚢"},{"text":"Spoilage Hint","icon":"🤢"}]},{"id":"g4","color":"#c060c0","label":"Language of silence — pauses that speak","connection":"All are silences in the marketplace that carry meaning without any word","tiles":[{"text":"The Refusing Pause","icon":"🤐"},{"text":"The Considering Stillness","icon":"🧘"},{"text":"The Surprised Hush","icon":"😶"},{"text":"The Final Word Gap","icon":"⏸️"}]}]}',
 4, 4, '6-9'),

-- Day 27 · Mar 27 · Sudoku · Week 4
('2026-03-27', '2026-03-27', 'sudoku',
 '{"id":"sudoku_20260327","title":"The Star-Chart of the River Observatory","storyBeat":"Budhipur''s river observatory tracked six stars above the six bends of the great river.","hint":"Chatur says: ''Start where the numbers cluster most densely — that corner will unlock the rest.''","winMessage":"''The stars do not lie in their columns. Neither do numbers.''","grade":"5-8","category":"2.4","size":6,"digits":[1,2,3,4,5,6],"givens":[1,0,3,0,5,0,0,5,0,1,0,3,2,0,0,5,0,4,0,6,0,2,0,1,3,0,2,0,1,0,0,1,0,3,0,2],"solution":[1,2,3,4,5,6,4,5,6,1,2,3,2,3,1,5,6,4,5,6,4,2,3,1,3,4,2,6,1,5,6,1,5,3,4,2],"regions":[[0,1,2,6,7,8],[3,4,5,9,10,11],[12,13,14,18,19,20],[15,16,17,21,22,23],[24,25,26,30,31,32],[27,28,29,33,34,35]]}',
 5, 4, '5-8'),

-- Day 28 · Mar 28 · Flow · Week 4
('2026-03-28', '2026-03-28', 'flow',
 '{"id":"flow_20260328","title":"The Underground Granary Tunnels","storyBeat":"Beneath the Bazaar lay Budhipur''s oldest secret: a network of granary tunnels linking six storage chambers.","hint":"Chatur says: ''Reserve the central passages for the route that needs them most, and do not begin at a corner — begin in the middle.''","winMessage":"The grain moved again. The new tunnel-master thanked Chatur with a sack of wheat flour that was taller than she was.","grade":"7-9","category":"1.2","grid":6,"pairs":[{"id":"R","color":"#e05050","start":[0,0],"end":[4,4]},{"id":"B","color":"#4a90d9","start":[0,2],"end":[5,1]},{"id":"G","color":"#3a7d44","start":[0,5],"end":[5,2]},{"id":"Y","color":"#e8a820","start":[1,1],"end":[4,5]},{"id":"P","color":"#9b59b6","start":[2,3],"end":[5,0]},{"id":"O","color":"#e8803a","start":[1,4],"end":[3,0]}]}',
 6, 4, '7-9'),

-- Day 29 · Mar 29 · Deduction · Week 5
('2026-03-29', '2026-03-29', 'deduction',
 '{"id":"deduction_20260329","title":"Mystery: The Five Missing Tokens of the Bazaar Council","storyBeat":"The Bazaar Council used five brass tokens to open the city''s great locked gate on festival mornings. The night before the closing ceremony, all five tokens vanished.","hint":"Chatur says: ''Match each councillor to the quarter they secretly favour, then match the quarter to where they would hide something familiar.''","winMessage":"By dawn all five tokens were recovered and the gate opened exactly on time.","grade":"7-10","category":"2.1","categories":[{"name":"Councillor","icon":"👤","items":[{"name":"Head Councillor Devi","icon":"👩‍⚖️"},{"name":"Councillor Basu","icon":"🧔"},{"name":"Councillor Rani","icon":"👸"},{"name":"Councillor Mohan","icon":"🧑‍🌾"}]},{"name":"Hiding Place","icon":"🗺️","items":[{"name":"River Ghat Steps","icon":"🪜"},{"name":"Archive Roof","icon":"🏛️"},{"name":"School Bell Tower","icon":"🔔"},{"name":"Spice Vault","icon":"🌶️"}]}],"clues":[{"id":1,"text":"Head Councillor Devi is afraid of heights — she would never climb to the Archive Roof or the School Bell Tower."},{"id":2,"text":"Councillor Basu''s family has stored things at the Spice Vault for three generations."},{"id":3,"text":"Councillor Rani was seen near the Archive at midnight, and the Archive Roof is accessible only through the Archive."},{"id":4,"text":"Councillor Mohan grows up as a river-child and still goes to the Ghat every Sunday morning before dawn."},{"id":5,"text":"The token hidden at the River Ghat Steps was left under the third step — a place only someone who visits regularly would know."}],"solution":{"Councillor":"Councillor Rani","Hiding Place":"Archive Roof"}}',
 0, 5, '7-10'),

-- Day 30 · Mar 30 · Flow · Week 5
('2026-03-30', '2026-03-30', 'flow',
 '{"id":"flow_20260330","title":"Chatur''s Last Chalk Line","storyBeat":"On the last Monday of March, Chatur sat alone in the school courtyard with a piece of chalk, drawing the month''s final puzzle for herself.","hint":"Chatur says: ''When the puzzle is for yourself, you are the most honest solver. No guessing — only knowing, one step at a time.''","winMessage":"The courtyard was covered in chalk lines, beautiful and exact, every square touched, every colour matched.","grade":"7-9","category":"1.2","grid":6,"pairs":[{"id":"R","color":"#e05050","start":[0,0],"end":[5,4]},{"id":"B","color":"#4a90d9","start":[0,3],"end":[5,0]},{"id":"G","color":"#3a7d44","start":[0,5],"end":[4,1]},{"id":"Y","color":"#e8a820","start":[1,2],"end":[5,5]},{"id":"P","color":"#9b59b6","start":[2,4],"end":[4,0]},{"id":"O","color":"#e8803a","start":[1,0],"end":[3,5]}]}',
 1, 5, '7-9'),

-- Day 31 · Mar 31 · Connections · Week 5
('2026-03-31', '2026-03-31', 'connections',
 '{"id":"connections_20260331","title":"Everything Chatur Learned in March","storyBeat":"On the last day of March, Chatur sat on the steps of the Old Archive and opened her notebook.","hint":"Chatur says: ''This final puzzle holds everything the month taught you. The last group is the hardest because it sounds like the easiest.''","winMessage":"Chatur sorted the last tile and closed her notebook. The Archivist said: ''Same time next month?'' She was already walking toward the Bazaar.","grade":"7-9","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Things Budhipur does at the end of each month","connection":"All are rituals or customs performed on the last day of the month","tiles":[{"text":"Account-Settling","icon":"📒"},{"text":"River-Greeting","icon":"🙏"},{"text":"Lamp-Counting","icon":"🪔"},{"text":"Archive-Sealing","icon":"🔒"}]},{"id":"g2","color":"#4a90d9","label":"Things that begin again each new month","connection":"All are things in Budhipur that reset or restart with the new month","tiles":[{"text":"Market Quota","icon":"📦"},{"text":"Ferryman''s Log","icon":"📓"},{"text":"School Timetable","icon":"📅"},{"text":"Bridge Toll","icon":"💰"}]},{"id":"g3","color":"#e8a820","label":"Things Chatur solved in March","connection":"All are mysteries Chatur untangled over the course of the month","tiles":[{"text":"The Missing Saffron","icon":"🌸"},{"text":"The Vanished Scroll","icon":"📜"},{"text":"The Festival Drum","icon":"🥁"},{"text":"The Forged Seal","icon":"🔴"}]},{"id":"g4","color":"#c060c0","label":"Things that are both endings and beginnings","connection":"All are moments that are simultaneously a conclusion and a new start","tiles":[{"text":"Dawn","icon":"🌅"},{"text":"Empty Notebook","icon":"📔"},{"text":"Last Step Home","icon":"👣"},{"text":"First Question","icon":"❓"}]}]}',
 2, 5, '7-9')

ON CONFLICT (id) DO UPDATE SET
  engine_type = EXCLUDED.engine_type,
  config      = EXCLUDED.config,
  day_of_week = EXCLUDED.day_of_week,
  week_number = EXCLUDED.week_number,
  grade_band  = EXCLUDED.grade_band;
