-- ============================================================
-- seed-feb-2026.sql — Yosi Backdated Puzzles, Feb 19–28 2026
-- Run in Supabase SQL editor (paste entire file)
-- ============================================================

INSERT INTO puzzles (id, puzzle_date, engine_type, config, day_of_week, week_number, grade_band) VALUES

-- ─── Feb 19 · Thursday · Deduction 2×2 · Week 3 ───────────
('2026-02-19', '2026-02-19', 'deduction',
 '{"id":"deduction_20260219","title":"Mystery: The Stolen Clapper","storyBeat":"The temple bell rang hollow at dawn — its iron clapper was missing. Old Gupta the bell-keeper stood wringing his hands as Chatur arrived. Two figures had been near the temple that morning. ''Two suspects, two places,'' said Chatur, opening her notebook. ''Let us sort this quickly.''","hint":"Chatur says: ''One clue tells you exactly where one person was standing. The other clue tells you where the clapper was last heard. Put them together and one answer remains.''","winMessage":"The clapper was found tucked in a sack at the Old Granary — Vikram admitted he had borrowed it to test its tone for the Festival. Chatur marked her notebook: ''Curiosity, not malice.''","grade":"1-3","category":"2.1","categories":[{"name":"Suspect","icon":"🧑","items":[{"name":"Vikram","icon":"👨"},{"name":"Sona","icon":"👩"}]},{"name":"Location","icon":"📍","items":[{"name":"Old Granary","icon":"🏚️"},{"name":"Clock Tower","icon":"🕰️"}]}],"clues":[{"id":1,"text":"Sona was seen drawing water at the well beside the Clock Tower at the very time the clapper went missing — witnesses confirm she never left that spot."},{"id":2,"text":"The temple bell was heard ringing faintly, with a dull clunk, from inside the Old Granary just before dawn."}],"solution":{"Suspect":"Vikram","Location":"Old Granary"}}',
 3, 3, '1-3'),

-- ─── Feb 20 · Friday · Lateral Thinking · Week 3 ──────────
('2026-02-20', '2026-02-20', 'lateral',
 '{"id":"lateral_20260220","title":"The Stone and the River","storyBeat":"Hari sat on the ferry with a large iron stone in his lap, watching the river. ''What happens,'' asked Chatur, ''if that stone slips overboard and sinks to the bottom? The ferry is still floating. Does the river level rise, fall, or stay the same?'' Hari shrugged. Chatur smiled and waited.","hint":"Chatur says: ''A floating boat displaces water equal to its weight. A sunken stone displaces water equal to its volume only. Iron is very heavy for its size — much heavier than an equal volume of water.''","winMessage":"''The river level falls!'' said Hari. ''The stone pushes less water aside when it is sunken than when it was weighing down the boat!'' Chatur nodded. ''Now you are thinking like the river.''","grade":"5-8","category":"3.2","prompt":"A clay ferry boat carries a large iron stone. The stone slips overboard and sinks to the riverbed. The boat is still floating. Compared to when the stone was in the boat — what happens to the river level?","options":[{"text":"Rises — the sunken stone still pushes water upward from below","icon":"📈"},{"text":"Falls — the submerged stone displaces less water than it did when it was weighing down the boat","icon":"📉"},{"text":"Stays the same — the stone''s total weight has not changed","icon":"➡️"},{"text":"Cannot tell without knowing the exact size of the stone","icon":"❓"}],"correctIndex":1,"explanation":"When the stone was in the boat, the boat displaced water equal to the combined weight of boat and stone. Once the stone sinks, it only displaces water equal to its own volume. Because iron is far denser than water, its volume is much smaller than the equivalent weight of water — so total water displaced drops, and the river level falls."}',
 4, 3, '5-8'),

-- ─── Feb 21 · Saturday · Sudoku 6×6 · Week 3 ──────────────
('2026-02-21', '2026-02-21', 'sudoku',
 '{"id":"sudoku_20260221","title":"The Archive''s Six Great Shelves","storyBeat":"The Archivist had six kinds of scrolls and six shelves — six rows, six columns, six tidy blocks. ''Every kind of scroll,'' he told young Hari, ''appears exactly once in each row, each column, and each block of six. Not a single scroll is ever doubled. Order, above all things.''","hint":"Chatur says: ''Work the 2×3 blocks first — they give you the most constraints at once. Find a block where five kinds are already placed and the sixth writes itself in.''","winMessage":"Hari placed the last scroll perfectly. The Archivist ran his finger along every row and column without a word. Then: ''Correct.'' That was considered high praise.","grade":"4-7","category":"2.4","size":6,"digits":[1,2,3,4,5,6],"givens":[1,0,3,0,5,6,0,5,0,1,0,3,2,0,0,5,6,0,0,6,4,0,3,0,3,0,2,0,0,5,0,4,0,3,0,2],"solution":[1,2,3,4,5,6,4,5,6,1,2,3,2,3,1,5,6,4,5,6,4,2,3,1,3,1,2,6,4,5,6,4,5,3,1,2],"regions":[[0,1,2,6,7,8],[3,4,5,9,10,11],[12,13,14,18,19,20],[15,16,17,21,22,23],[24,25,26,30,31,32],[27,28,29,33,34,35]]}',
 5, 3, '4-7'),

-- ─── Feb 22 · Sunday · Word Ladder · Week 4 ───────────────
('2026-02-22', '2026-02-22', 'word',
 '{"id":"word_20260222","title":"Chatur''s Word Path","storyBeat":"''Words are like river stones,'' Chatur told Hari, placing two pebbles on the step — one for BAKE, one for LATE. ''Change one letter at a time and you can walk from any word to any other — if you know the path.'' She looked at him. ''Six steps. No leaps.''","hint":"Chatur says: ''Try changing the last letter of BAKE first. Think of 4-letter words that differ by only one letter. Work one step at a time — every word must be real.''","winMessage":"BAKE → BARE → CARE → CAME → GAME → GATE → LATE. Hari traced the path with his finger. ''Seven stepping stones,'' he said, ''and never once a leap.'' Chatur smiled and pocketed her pebbles.","grade":"4-7","category":"3.1","mode":"word-ladder","startWord":"BAKE","endWord":"LATE","wordLength":4,"validPath":["BARE","CARE","CAME","GAME","GATE"]}',
 6, 4, '4-7'),

-- ─── Feb 23 · Monday · Lateral (balance puzzle) · Week 4 ──
('2026-02-23', '2026-02-23', 'lateral',
 '{"id":"lateral_20260223","title":"Weights of the Spice Market","storyBeat":"The spice merchant set three coconuts on one side of his balance scale and six bananas on the other. The scale levelled perfectly. He then took one coconut aside and placed two bananas in its place, and balanced the whole thing against a single pumpkin. The scale levelled again. Chatur turned to Hari. ''How many bananas weigh as much as one pumpkin?''","hint":"Chatur says: ''First find out how much one coconut weighs in bananas. Then use the second equation to find the pumpkin.''","winMessage":"''Four bananas!'' said Hari. Chatur nodded. ''Three coconuts equal six bananas, so one coconut equals two bananas. One coconut plus two bananas is two plus two — four bananas. The pumpkin tips at exactly four.'' The merchant looked genuinely impressed.","grade":"4-8","category":"3.3","prompt":"At the market stall: 3 coconuts balance exactly with 6 bananas. Then: 1 coconut and 2 bananas together balance exactly with 1 pumpkin. How many bananas weigh the same as 1 pumpkin?","options":[{"text":"2 bananas","icon":"🍌"},{"text":"3 bananas","icon":"🍌🍌"},{"text":"4 bananas","icon":"🍌🍌🍌"},{"text":"8 bananas","icon":"🍌🍌🍌🍌"}],"correctIndex":2,"explanation":"Since 3 coconuts = 6 bananas, dividing both sides by 3 gives: 1 coconut = 2 bananas. Substitute into the second equation: 1 pumpkin = 1 coconut + 2 bananas = 2 bananas + 2 bananas = 4 bananas."}',
 0, 4, '4-8'),

-- ─── Feb 24 · Tuesday · Visual Pattern · Week 4 ───────────
('2026-02-24', '2026-02-24', 'visual',
 '{"id":"visual_20260224","title":"What Sinks in the River?","storyBeat":"Chatur lined up five things on the edge of the ghat. ''Four of these belong together,'' she said. ''One does not. Which one would sink straight to the riverbed — and why does everything else float?''","hint":"Chatur says: ''Think about density — whether the object is lighter or heavier than the water it would push aside if you dropped it in.''","winMessage":"''The iron anchor!'' said Hari. Chatur tossed a dry leaf onto the current and watched it drift downstream. ''The river keeps its secrets at the bottom,'' she said, ''and everything else at the surface.''","grade":"2-5","category":"3.2","mode":"odd-one-out","items":[{"text":"Lotus Leaf","icon":"🪷"},{"text":"Coconut Shell","icon":"🥥"},{"text":"Iron Anchor","icon":"⚓"},{"text":"Dry Gourd","icon":"🎃"},{"text":"Wooden Plank","icon":"🪵"}],"correctIndex":2,"explanation":"A lotus leaf, coconut shell, dry gourd, and wooden plank all float because they are less dense than water (or trap air). An iron anchor is far denser than water — it sinks straight to the riverbed the moment it enters the water."}',
 1, 4, '2-5'),

-- ─── Feb 25 · Wednesday · Connections · Week 4 ────────────
('2026-02-25', '2026-02-25', 'connections',
 '{"id":"connections_20260225","title":"Chatur Sorts the Lane","storyBeat":"Chatur tipped sixteen small objects onto the courtyard floor. ''Four groups of four,'' she told Hari. ''Three groups have clear trades or materials. But the fourth — even I had to think twice.'' She stepped back and waited.","hint":"Chatur says: ''Three groups sort themselves by craft or material. The fourth group shares something you cannot see or touch. Look for a hidden word that connects all four objects.''","winMessage":"Hari sorted the first three groups in minutes. The fourth stopped him. ''They all have an eye!'' he said at last — the needle''s eye, the eye of a storm, a potato''s eye-bud, the eye-spot on a peacock feather. Chatur applauded, once, slowly.","grade":"5-8","category":"4.3","groups":[{"id":"g1","color":"#3a7d44","label":"Used by the water-carrier","connection":"All are carried or used by Budhipur''s water-carriers on their daily rounds","tiles":[{"text":"Clay Pot","icon":"🏺"},{"text":"Copper Vessel","icon":"🪣"},{"text":"Bamboo Yoke","icon":"🎋"},{"text":"Hemp Rope","icon":"🪢"}]},{"id":"g2","color":"#4a90d9","label":"Used to write or inscribe","connection":"All are tools used to write or engrave records in the Budhipur Archive","tiles":[{"text":"Reed Pen","icon":"✒️"},{"text":"Inkpot","icon":"🖋️"},{"text":"Copper Plate","icon":"🥉"},{"text":"Clay Tablet","icon":"🪨"}]},{"id":"g3","color":"#e8a820","label":"Seeds from the spice market","connection":"All are seeds traded at the Budhipur spice quarter","tiles":[{"text":"Mustard","icon":"🌱"},{"text":"Cumin","icon":"🌿"},{"text":"Fenugreek","icon":"🫘"},{"text":"Sesame","icon":"⚪"}]},{"id":"g4","color":"#c060c0","label":"All have an EYE","connection":"All share a hidden ''eye'': the needle''s eye, the eye of a storm, a potato''s eye-bud, and the eye-spot on a peacock feather","tiles":[{"text":"Needle","icon":"🪡"},{"text":"Storm","icon":"🌀"},{"text":"Potato","icon":"🥔"},{"text":"Peacock Feather","icon":"🦚"}]}]}',
 2, 4, '5-8'),

-- ─── Feb 26 · Thursday · Deduction 4×4 · Week 4 ──────────
('2026-02-26', '2026-02-26', 'deduction',
 '{"id":"deduction_20260226","title":"Mystery: The Night of the Missing Lanterns","storyBeat":"Four lanterns were stolen from four corners of Budhipur on the same night — the Bell Tower, the Cellar of the old inn, the River Steps, and the Rooftop of the dyers'' quarter. Four suspects were out that night. Chatur arrived at first light, notebook in hand. ''One clue at a time,'' she said. ''And the lane reveals everything.''","hint":"Chatur says: ''Start with the clues that place someone definitively — heights, water, echoes each name a location. Once three suspects are placed, the fourth follows by elimination.''","winMessage":"Arjun at the Bell Tower. Mira in the Cellar. Devesh at the River Steps. Sona on the Rooftop. ''How?'' asked the inspector. ''Clues,'' said Chatur. ''And the smell of river mud on Devesh''s sandals.''","grade":"5-8","category":"2.1","categories":[{"name":"Suspect","icon":"🧑","items":[{"name":"Arjun","icon":"👦"},{"name":"Mira","icon":"👩"},{"name":"Devesh","icon":"🧔"},{"name":"Sona","icon":"👧"}]},{"name":"Location","icon":"📍","items":[{"name":"Bell Tower","icon":"🔔"},{"name":"Cellar","icon":"🏚️"},{"name":"River Steps","icon":"🌊"},{"name":"Rooftop","icon":"🏠"}]}],"clues":[{"id":1,"text":"Sona was spotted from the market square, her silhouette clearly visible against the stars — she was at the highest point in the lane that night."},{"id":2,"text":"Mira''s voice drifted up through the stone flags, low and echoing — she was in a deeply enclosed underground space, not outdoors or elevated."},{"id":3,"text":"Devesh''s sandals were thick with river mud when he was found the next morning — he had been near the water all night, nowhere else."},{"id":4,"text":"The Bell Tower lantern was taken by the one suspect not yet placed by clues 1 through 3."}],"solution":{"Suspect":"Arjun","Location":"Bell Tower"}}',
 3, 4, '5-8'),

-- ─── Feb 27 · Friday · Lateral (nine scrolls) · Week 4 ────
('2026-02-27', '2026-02-27', 'lateral',
 '{"id":"lateral_20260227","title":"The Nine Scrolls","storyBeat":"The Archivist had nine scrolls that looked completely identical — but one was slightly heavier than the rest. He had only a balance scale and no weights. ''I must find the heavy scroll,'' he told Chatur. ''What is the fewest number of weighings I need to guarantee finding it?'' Chatur did not hesitate.","hint":"Chatur says: ''Do not weigh them one by one — that wastes weighings. Think about how to split them into groups so each single weighing eliminates as many scrolls as possible at once.''","winMessage":"''Two weighings,'' said Chatur. ''Divide nine into three groups of three. Weigh group one against group two. If they balance, the heavy scroll is in group three. If one side is heavier, it is in that group. Now take those three scrolls and weigh any two of them. If they balance, the third is heavy. If not, the heavier side holds it. Two weighings — always enough.'' The Archivist bowed.","grade":"5-9","category":"3.3","prompt":"The Archivist has 9 identical-looking scrolls. Exactly one is heavier than the rest. He has a balance scale (no weights). What is the MINIMUM number of weighings guaranteed to always find the heavy scroll?","options":[{"text":"1 weighing","icon":"1️⃣"},{"text":"2 weighings","icon":"2️⃣"},{"text":"3 weighings","icon":"3️⃣"},{"text":"4 weighings","icon":"4️⃣"}],"correctIndex":1,"explanation":"Divide the 9 scrolls into 3 groups of 3. Weigh group 1 vs group 2. If they balance, the heavy scroll is in group 3. If one side is heavier, it is in that group. You now have 3 suspect scrolls. Weigh any 2 of them: if they balance, the third is heavy; if not, the heavier side holds it. Total: 2 weighings, always sufficient."}',
 4, 4, '5-9'),

-- ─── Feb 28 · Saturday · Sudoku 4×4 Emoji Stars · Week 4 ──
('2026-02-28', '2026-02-28', 'sudoku',
 '{"id":"sudoku_20260228","title":"The Star-Counter''s Grid","storyBeat":"The temple astronomer kept count of the night sky with four kinds of stars — bright stars ⭐, glowing stars 🌟, spinning stars 💫, and sparkling stars ✨. She arranged them in a four-by-four grid where every row, every column, and every square of four held each kind of star exactly once. ''Can you complete her count?'' she asked Hari.","hint":"Chatur says: ''Every row, column, and 2×2 square must hold all four star symbols. Start with the row or box that already has the most stars filled in.''","winMessage":"The grid was complete: every row, column, and square of four held all four kinds of star. The astronomer looked up from her notebook. ''The sky is in order,'' she said simply.","grade":"2-5","category":"2.4","size":4,"digits":["⭐","🌟","💫","✨"],"givens":["⭐",0,0,"✨",0,"✨",0,0,"🌟",0,0,0,0,0,"🌟","⭐"],"solution":["⭐","🌟","💫","✨","💫","✨","⭐","🌟","🌟","⭐","✨","💫","✨","💫","🌟","⭐"],"regions":[[0,1,4,5],[2,3,6,7],[8,9,12,13],[10,11,14,15]]}',
 5, 4, '2-5');
